title: Asmaa Hadir # your name (or website title) here
logo: "images/copy_75998514.png" # your photo (or logo) here


description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Intern  
  <br><br>
  Computer Science Student 
  <br><br>
  <a href="https://www.linkedin.com/in/asmaa-hadir/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
